repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        types: [file]
        files: \.(h|c|cpp)$
    -   id: trailing-whitespace
        types: [file]
        files: \.(h|c|cpp)$
        exclude_types: [cmake]
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/smavridis/pre-commit-hooks
    rev: 57f5d6f
    hooks:
    -   id: uncrustify
        args: [-q, -c=.uncrustify.cfg, --replace, --no-backup]
        types: [file]
        files: \.(h|c|cpp)$
        exclude_types: [cmake]
        exclude: ^3rdparty/
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -    id: gitlint
         stages: [commit-msg]
         entry: gitlint
         args: [--contrib=CT1,--ignore,body-is-missing, --msg-filename]
