Arax: arax_plot.h File Reference
arax_plot.h File Reference
#include <stdint.h>
#include <arax.h>
Functions
uint64_t * arax_plot_register_metric (const char *name, uint64_t *metric)
Function Documentation
arax_plot_register_metric()
uint64_t * arax_plot_register_metric (const char * name, uint64_t * metric)
Register a new metric name and set/get the location where its value resides.
The value pointer metric can be null or a valid arax pointer. When null, the call will allocate space for the metric, and return the pointer. When given a pointer where arax_ptr_valid()==true, the provided pointer is used and returned.
Note
This should be called before starting the arax_plot executable.
Parameters
name Short name of new metric.
metric NULL or pointer that has arax_ptr_valid()==true.
Returns
Pointer location of metric.
Definition at line 7 of file arax_plot.c.
References arax_assert, arax_init(), arax_ptr_valid(), arch_alloc_allocate(), utils_kv_set(), and vpipe.