Arax: malloc.h File Reference
malloc.h File Reference
#include <stddef.h>
Data Structures
struct mallinfo
Macros
#define ONLY_MSPACES 0 /* define to a value */
#define NO_MALLINFO 0
#define MSPACES 0
#define dlcalloc calloc
#define dlfree free
#define dlmalloc malloc
#define dlmemalign memalign
#define dlposix_memalign posix_memalign
#define dlrealloc realloc
#define dlvalloc valloc
#define dlpvalloc pvalloc
#define dlmallinfo
#define dlmallopt mallopt
#define dlmalloc_trim malloc_trim
#define dlmalloc_stats
#define dlmalloc_usable_size malloc_usable_size
#define dlmalloc_footprint
#define dlmalloc_max_footprint
#define dlmalloc_footprint_limit
#define dlmalloc_set_footprint_limit malloc_set_footprint_limit
#define dlmalloc_inspect_all malloc_inspect_all
#define dlindependent_calloc independent_calloc
#define dlindependent_comalloc independent_comalloc
#define dlbulk_free bulk_free
#define MALLINFO_FIELD_TYPE size_t
#define STRUCT_MALLINFO_DECLARED 1
#define M_TRIM_THRESHOLD (-1)
#define M_GRANULARITY (-2)
#define M_MMAP_THRESHOLD (-3)
Functions
void * dlmalloc (size_t)
void dlfree (void *)
void * dlcalloc (size_t, size_t)
void * dlrealloc (void *, size_t)
void * dlrealloc_in_place (void *, size_t)
void * dlmemalign (size_t, size_t)
int dlposix_memalign (void **, size_t, size_t)
void * dlvalloc (size_t)
int dlmallopt (int, int)
size_t dlmalloc_set_footprint_limit (size_t bytes)
void dlmalloc_inspect_all (void(*handler)(void *, void *, size_t, void *), void *arg)
void ** dlindependent_calloc (size_t, size_t, void **)
void ** dlindependent_comalloc (size_t, size_t *, void **)
size_t dlbulk_free (void **, size_t n_elements)
void * dlpvalloc (size_t)
int dlmalloc_trim (size_t)
size_t dlmalloc_usable_size (const void *)
Macro Definition Documentation
dlbulk_free
#define dlbulk_free bulk_free
Definition at line 72 of file malloc.h.
dlcalloc
#define dlcalloc calloc
Definition at line 52 of file malloc.h.
dlfree
#define dlfree free
Definition at line 53 of file malloc.h.
dlindependent_calloc
#define dlindependent_calloc independent_calloc
Definition at line 70 of file malloc.h.
dlindependent_comalloc
#define dlindependent_comalloc independent_comalloc
Definition at line 71 of file malloc.h.
dlmallinfo
#define dlmallinfo (void)
Value:
mallinfo
Definition at line 60 of file malloc.h.
dlmalloc
#define dlmalloc malloc
Definition at line 54 of file malloc.h.
dlmalloc_footprint
#define dlmalloc_footprint (void)
Value:
malloc_footprint
Definition at line 65 of file malloc.h.
dlmalloc_footprint_limit
#define dlmalloc_footprint_limit (void)
Value:
malloc_footprint_limit
Definition at line 67 of file malloc.h.
dlmalloc_inspect_all
#define dlmalloc_inspect_all malloc_inspect_all
Definition at line 69 of file malloc.h.
dlmalloc_max_footprint
#define dlmalloc_max_footprint (void)
Value:
malloc_max_footprint
Definition at line 66 of file malloc.h.
dlmalloc_set_footprint_limit
#define dlmalloc_set_footprint_limit malloc_set_footprint_limit
Definition at line 68 of file malloc.h.
dlmalloc_stats
#define dlmalloc_stats (void)
Value:
malloc_stats
Definition at line 63 of file malloc.h.
dlmalloc_trim
#define dlmalloc_trim malloc_trim
Definition at line 62 of file malloc.h.
dlmalloc_usable_size
#define dlmalloc_usable_size malloc_usable_size
Definition at line 64 of file malloc.h.
dlmallopt
#define dlmallopt mallopt
Definition at line 61 of file malloc.h.
dlmemalign
#define dlmemalign memalign
Definition at line 55 of file malloc.h.
dlposix_memalign
#define dlposix_memalign posix_memalign
Definition at line 56 of file malloc.h.
dlpvalloc
#define dlpvalloc pvalloc
Definition at line 59 of file malloc.h.
dlrealloc
#define dlrealloc realloc
Definition at line 57 of file malloc.h.
dlvalloc
#define dlvalloc valloc
Definition at line 58 of file malloc.h.
M_GRANULARITY
#define M_GRANULARITY (-2)
Definition at line 222 of file malloc.h.
M_MMAP_THRESHOLD
#define M_MMAP_THRESHOLD (-3)
Definition at line 223 of file malloc.h.
M_TRIM_THRESHOLD
#define M_TRIM_THRESHOLD (-1)
Definition at line 221 of file malloc.h.
MALLINFO_FIELD_TYPE
#define MALLINFO_FIELD_TYPE size_t
Definition at line 79 of file malloc.h.
MSPACES
#define MSPACES 0
Definition at line 45 of file malloc.h.
NO_MALLINFO
#define NO_MALLINFO 0
Definition at line 38 of file malloc.h.
ONLY_MSPACES
#define ONLY_MSPACES 0 /* define to a value */
Definition at line 33 of file malloc.h.
STRUCT_MALLINFO_DECLARED
#define STRUCT_MALLINFO_DECLARED 1
Definition at line 82 of file malloc.h.
Function Documentation
dlbulk_free()
size_t dlbulk_free (void ** , size_t n_elements)
dlcalloc()
void * dlcalloc (size_t n_elements, size_t elem_size)
Definition at line 4893 of file malloc.c.
References calloc_must_clear, dlmalloc, MAX_SIZE_T, and mem2chunk.
dlfree()
void dlfree (void * mem)
Definition at line 4788 of file malloc.c.
References CALL_MUNMAP, check_free_chunk, check_inuse_chunk, chunk_minus_offset, chunk_plus_offset, chunksize, cinuse, fm, malloc_chunk::head, insert_large_chunk, insert_small_chunk, INUSE_BITS, is_mmapped, is_small, mem2chunk, MMAP_FOOT_PAD, ok_address, ok_inuse, ok_magic, ok_next, ok_pinuse, pinuse, PINUSE_BIT, POSTACTION, PREACTION, malloc_chunk::prev_foot, release_unused_segments(), RTCHECK, set_free_with_pinuse, set_size_and_pinuse_of_free_chunk, should_trim, sys_trim(), unlink_chunk, and USAGE_ERROR_ACTION.
dlindependent_calloc()
void ** dlindependent_calloc (size_t , size_t , void **)
dlindependent_comalloc()
void ** dlindependent_comalloc (size_t , size_t * , void **)
dlmalloc()
void * dlmalloc (size_t bytes)
Definition at line 4657 of file malloc.c.
References assert, check_malloced_chunk, check_top_chunk, chunk2mem, chunk_plus_offset, chunksize, compute_bit2idx, ensure_initialization, malloc_chunk::fd, gm, malloc_chunk::head, idx2bit, least_bit, left_bits, MAX_REQUEST, MAX_SIZE_T, MAX_SMALL_REQUEST, MIN_CHUNK_SIZE, MIN_REQUEST, pad_request, PINUSE_BIT, POSTACTION, PREACTION, replace_dv, set_inuse_and_pinuse, set_size_and_pinuse_of_free_chunk, set_size_and_pinuse_of_inuse_chunk, SIZE_T_SIZE, small_index, small_index2size, smallbin_at, sys_alloc(), tmalloc_large(), tmalloc_small(), and unlink_first_small_chunk.
dlmalloc_inspect_all()
void dlmalloc_inspect_all (void(* handler)(void *, void *, size_t, void *), void * arg)
References dlmallinfo.
dlmalloc_set_footprint_limit()
size_t dlmalloc_set_footprint_limit (size_t bytes)
Definition at line 5478 of file malloc.c.
References gm, granularity_align, and MAX_SIZE_T.
dlmalloc_trim()
int dlmalloc_trim (size_t pad)
Definition at line 5449 of file malloc.c.
References ensure_initialization, gm, POSTACTION, PREACTION, and sys_trim().
dlmalloc_usable_size()
size_t dlmalloc_usable_size (const void *)
dlmallopt()
int dlmallopt (int param_number, int value)
Definition at line 5507 of file malloc.c.
References change_mparam().
dlmemalign()
void * dlmemalign (size_t alignment, size_t bytes)
Definition at line 5363 of file malloc.c.
References dlmalloc, gm, internal_memalign(), and MALLOC_ALIGNMENT.
dlposix_memalign()
int dlposix_memalign (void ** pp, size_t alignment, size_t bytes)
Definition at line 5371 of file malloc.c.
References dlmalloc, gm, internal_memalign(), MALLOC_ALIGNMENT, MAX_REQUEST, MIN_CHUNK_SIZE, and SIZE_T_ONE.
dlpvalloc()
void * dlpvalloc (size_t bytes)
Definition at line 5405 of file malloc.c.
References dlmemalign, ensure_initialization, mparams, and SIZE_T_ONE.
dlrealloc()
void * dlrealloc (void * oldmem, size_t bytes)
Definition at line 5286 of file malloc.c.
References check_inuse_chunk, chunk2mem, chunksize, dlfree, dlmalloc, gm, internal_free, internal_malloc, MALLOC_FAILURE_ACTION, MAX_REQUEST, mem2chunk, ok_magic, overhead_for, POSTACTION, PREACTION, request2size, try_realloc_chunk(), and USAGE_ERROR_ACTION.
dlrealloc_in_place()
void * dlrealloc_in_place (void * oldmem, size_t bytes)
Definition at line 5331 of file malloc.c.
References check_inuse_chunk, gm, MALLOC_FAILURE_ACTION, MAX_REQUEST, mem2chunk, ok_magic, POSTACTION, PREACTION, request2size, try_realloc_chunk(), and USAGE_ERROR_ACTION.
dlvalloc()
void * dlvalloc (size_t bytes)
Definition at line 5396 of file malloc.c.
References dlmemalign, ensure_initialization, and mparams.