Arax: Public Procedure user API
Public Procedure user API
Functions
arax_proc * arax_proc_register (const char *func_name)
arax_proc * arax_proc_get (const char *func_name)
int arax_proc_put (arax_proc *func)
Detailed Description
Functions usable from applications for manipulating Procedures.
Function Documentation
arax_proc_get()
arax_proc * arax_proc_get (const char * func_name)
Retrieve a previously registered arax_proc pointer.
Note
For every arax_proc_get()/arax_proc_register() there should be a matching call to arax_proc_put()
Parameters
func_name Descriptive name of function, as provided to arax_proc_register.
Returns
arax_proc * corresponding to the requested function, NULL on failure.
Definition at line 400 of file impl.c.
References arax_object_ref_inc(), arax_pipe_find_proc(), arax_pipe_get, arax_proc_s::obj, and vpipe.
Referenced by arax_data_allocate_remote(), arax_data_get(), arax_data_set(), and ARAX_OBJ_DTOR_DECL().
arax_proc_put()
int arax_proc_put (arax_proc * func)
Delete registered arax_proc pointer.
Note
For every arax_proc_get()/arax_proc_register() there should be a matching call to arax_proc_put()
Parameters
func arax_proc to be deleted.
Definition at line 413 of file impl.c.
References arax_object_ref_dec(), and arax_proc_s::obj.
Referenced by arax_data_get(), and arax_data_set().
arax_proc_register()
arax_proc * arax_proc_register (const char * func_name)
Register a new process 'func_name'. Processes are accelerator agnostic and initially have no 'implementations'/functors. Returned arax_proc * identifies given function globally.
Note
For every arax_proc_get()/arax_proc_register() there should be a matching call to arax_proc_put()
To add a functor/implementation see/use arax_proc_set_functor().
Parameters
func_name Descriptive name of function, has to be unique for given type.
Returns
arax_proc * corresponding to the registered function, NULL on failure.
Definition at line 384 of file impl.c.
References arax_pipe_find_proc(), arax_pipe_get, arax_proc_init(), and vpipe.