Arax: async.c File Reference
async.c File Reference
#include "async.h"
Functions
void async_meta_init_once (async_meta_s *meta, arch_alloc_s *alloc)
void async_meta_init_always (async_meta_s *meta)
void async_completion_init (async_meta_s *meta, async_completion_s *completion)
void async_completion_complete (async_completion_s *completion)
void async_completion_wait (async_completion_s *completion)
int async_completion_check (async_completion_s *completion)
void async_semaphore_init (async_meta_s *meta, async_semaphore_s *sem)
int async_semaphore_value (async_semaphore_s *sem)
void async_semaphore_inc (async_semaphore_s *sem)
void async_semaphore_dec (async_semaphore_s *sem)
void async_condition_init (async_meta_s *meta, async_condition_s *cond)
void async_condition_lock (async_condition_s *cond)
void async_condition_wait (async_condition_s *cond)
void async_condition_notify (async_condition_s *cond)
void async_condition_unlock (async_condition_s *cond)
void async_meta_exit (async_meta_s *meta)
Function Documentation
async_completion_check()
int async_completion_check (async_completion_s * completion)
Check if completion has been marked as completed.
Parameters
completion Completion to be checked.
Returns
0 if not completed, !0 if completed.
Definition at line 28 of file mutex/async.c.
References async_completion_s::mutex.
async_completion_complete()
void async_completion_complete (async_completion_s * completion)
Mark compl as completed and notify pending async_completion_wait() callers.
Parameters
completion Completion to be marked as completed.
Definition at line 17 of file mutex/async.c.
References async_completion_s::mutex.
Referenced by async_condition_unlock().
async_completion_init()
void async_completion_init (async_meta_s * meta, async_completion_s * completion)
Create and register async_completion_s objects created in buff.
Parameters
meta Pointer to async_meta_s that will 'own' this completion.
completion Completion to be initialized
Returns
Number of objects created, should be buff_size/async_completion_size().
Definition at line 9 of file mutex/async.c.
References async_completion_s::attr, and async_completion_s::mutex.
Referenced by async_condition_init().
async_completion_wait()
void async_completion_wait (async_completion_s * completion)
Wait for compl to be completed with async_completion_complete().
Parameters
completion Sleep untill it has been completed with async_completion_complete.
Definition at line 23 of file mutex/async.c.
References async_completion_s::mutex.
Referenced by async_condition_lock().
async_condition_init()
void async_condition_init (async_meta_s * meta, async_condition_s * cond)
Initialize semaphore.
Parameters
meta Pointer to async_meta_s that will 'own' this semaphore.
cond Condition to be initialized
Definition at line 60 of file mutex/async.c.
References async_completion_init(), async_condition_unlock(), async_condition_s::c_attr, async_condition_s::condition, and async_condition_s::mutex.
async_condition_lock()
void async_condition_lock (async_condition_s * cond)
Lock on condition cond.
Parameters
cond Condition to be read.
Definition at line 69 of file mutex/async.c.
References async_completion_wait(), and async_condition_s::mutex.
async_condition_notify()
void async_condition_notify (async_condition_s * cond)
Notify cond.
Note
Prior to this call cond must be locked using async_condition_lock().
Parameters
cond Condition to be notified.
Definition at line 79 of file mutex/async.c.
References async_condition_s::condition.
async_condition_unlock()
void async_condition_unlock (async_condition_s * cond)
Lock on condition cond.
Note
Prior to this call cond must be locked using async_condition_lock().
Parameters
cond Condition to be read.
Definition at line 84 of file mutex/async.c.
References async_completion_complete(), and async_condition_s::mutex.
Referenced by async_condition_init().
async_condition_wait()
void async_condition_wait (async_condition_s * cond)
Wait on cond.
Note
Prior to this call cond must be locked using async_condition_lock().
Parameters
cond Condition to be read.
Definition at line 74 of file mutex/async.c.
References async_condition_s::condition, async_completion_s::mutex, and async_condition_s::mutex.
async_meta_exit()
void async_meta_exit (async_meta_s * meta)
De initialize an async_meta_s object.
Parameters
meta The async_meta_s object to be uninitialized.
Definition at line 89 of file mutex/async.c.
async_meta_init_always()
void async_meta_init_always (async_meta_s * meta)
Initialize a async_meta_s object on every node.
This will be called multiple times, once for every node.
Parameters
meta An uninitialized async_meta_s object.
Definition at line 6 of file mutex/async.c.
async_meta_init_once()
void async_meta_init_once (async_meta_s * meta, arch_alloc_s * alloc)
Initialize a async_meta_s object once.
This will be called only once, on the first node.
Parameters
meta An uninitialized async_meta_s object.
alloc Allocator instance to be used for internall allocations.
Definition at line 3 of file mutex/async.c.
async_semaphore_dec()
void async_semaphore_dec (async_semaphore_s * sem)
Decrease semaphore.
Decrease(ie consume) sem by one. This function will block if async_semaphore_value() == 0.
Parameters
sem Semaphore to be increased.
Definition at line 55 of file mutex/async.c.
References async_semaphore_s::sem.
async_semaphore_inc()
void async_semaphore_inc (async_semaphore_s * sem)
Increase semaphore.
Increase(ie produce) sem by one. This function will never block.
Parameters
sem Semaphore to be increased.
Definition at line 50 of file mutex/async.c.
References async_semaphore_s::sem.
async_semaphore_init()
void async_semaphore_init (async_meta_s * meta, async_semaphore_s * sem)
Initialize semaphore.
Parameters
meta Pointer to async_meta_s that will 'own' this semaphore.
sem Semaphore to be initialized
Definition at line 37 of file mutex/async.c.
References async_semaphore_s::sem.
async_semaphore_value()
int async_semaphore_value (async_semaphore_s * sem)
Return value of sem.
Parameters
sem Semaphore to be initialized
Definition at line 42 of file mutex/async.c.
References async_semaphore_s::sem.