Arax: system.c File Reference
system.c File Reference
#include "system.h"
#include <sys/stat.h>
#include <string.h>
#include <execinfo.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <pwd.h>
Macros
#define FMT "%*s%*s"
#define MID(LEN, STR) (int) (LEN / 2 + strlen(STR)), STR, (int) (LEN / 2 - strlen(STR)), " "
Functions
size_t system_total_memory ()
char * system_home_path ()
off_t system_file_size (const char *file)
const char * system_exec_name ()
int system_process_id ()
int system_thread_id ()
char * formatStackLine (const char *bt_sym, int *cwidths, char *dest)
const char * system_backtrace (unsigned int skip)
Variables
static char __backtraceStr [32768]
Macro Definition Documentation
FMT
#define FMT "%*s%*s"
Definition at line 111 of file system.c.
MID
#define MID (LEN, STR) (int) (LEN / 2 + strlen(STR)), STR, (int) (LEN / 2 - strlen(STR)), " "
Definition at line 112 of file system.c.
Function Documentation
formatStackLine()
char * formatStackLine (const char * bt_sym, int * cwidths, char * dest)
Definition at line 63 of file system.c.
Referenced by system_backtrace().
system_backtrace()
const char * system_backtrace (unsigned int skip)
Get stack backtrace for calling thread. Returned string does not end with a new line.
Note
Do not free or modify returned value
Parameters
skip Number of functions to skip from trace.0 will show up to the caller.
Returns
formated acktrace
Definition at line 116 of file system.c.
References __backtraceStr, FMT, formatStackLine(), and MID.
Referenced by _arax_assert().
system_exec_name()
const char * system_exec_name ()
Get current executable name
Definition at line 40 of file system.c.
system_file_size()
off_t system_file_size (const char * file)
Get size of file in bytes.
Returns
File size in bytes, 0 on failure.
Definition at line 30 of file system.c.
Referenced by _arax_init().
system_home_path()
char * system_home_path ()
Get current users home directory.
Note
Do NOT free returned pointer.
Returns
NULL terminated string with home path.
Definition at line 19 of file system.c.
Referenced by utils_config_alloc_path().
system_process_id()
int system_process_id ()
Get PID of current process
Definition at line 53 of file system.c.
Referenced by _arax_init(), and arax_exit().
system_thread_id()
int system_thread_id ()
Get thread id of current process thread
Definition at line 58 of file system.c.
system_total_memory()
size_t system_total_memory ()
Return total memory in bytes.
Returns
Total memory in bytes.
Definition at line 11 of file system.c.
Referenced by _arax_init().
Variable Documentation
__backtraceStr
char __backtraceStr[32768] static
Definition at line 114 of file system.c.
Referenced by system_backtrace().