Arax: config.c File Reference
config.c File Reference
#include "config.h"
#include "system.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
#include <stdint.h>
#include "utils/arax_assert.h"
#include <pwd.h>
Functions
void utils_config_write_long (char *path, const char *key, long value)
void utils_config_write_str (char *path, const char *key, const char *value)
char * utils_config_alloc_path (const char *path)
void utils_config_free_path (char *path)
int _utils_config_get_str (char *path, const char *key, char *value, size_t value_size)
int utils_config_get_str (char *path, const char *key, char *value, size_t value_size, const char *def_val)
int utils_config_get_bool (char *path, const char *key, int *value, int def_val)
int utils_config_get_int (char *path, const char *key, int *value, int def_val)
int utils_config_get_long (char *path, const char *key, long *value, long def_val)
int utils_config_get_size (char *path, const char *key, size_t *value, size_t def_val)
Function Documentation
_utils_config_get_str()
int _utils_config_get_str (char * path, const char * key, char * value, size_t value_size)
Definition at line 70 of file config.c.
Referenced by utils_config_get_long(), and utils_config_get_str().
utils_config_alloc_path()
char * utils_config_alloc_path (const char * path)
Create configuration based on path
NOTE: free returned value with utils_config_free_path().
path is scanned for the following characters and replaced: ~:Gets replaced with users home path (e.g. /home/user)
Parameters
path
Returns
NULL on failure
Definition at line 31 of file config.c.
References arax_assert, and system_home_path().
Referenced by _arax_init(), arax_clean(), async_meta_init_always(), and async_meta_init_once().
utils_config_free_path()
void utils_config_free_path (char * path)
Free path allocated with utils_config_alloc_path.
Parameters
path Return value of a utils_config_alloc_path invocation.
Definition at line 65 of file config.c.
Referenced by arax_clean(), arax_exit(), async_meta_init_always(), and async_meta_init_once().
utils_config_get_bool()
int utils_config_get_bool (char * path, const char * key, int * value, int def_val)
Get value corresponding to key as a boolean (0,1)
Will search the path file for a key/value pair matching the key. If the value is not found 0 will be returned. If during the search any error occurs, 0 will be returned and a message will be printed on stderr. If the value is found and the value equals to 1 then *value will be assigned 1, otherwise *value will be set to 0.
Note
This is a very slow function, use it only during initialization.
Parameters
path Config path.
key c style string, with the key of interest.
value pointer to allocated array of size value_size.
def_val Default value in case the key is not found.
Returns
Zero on failure.
Definition at line 112 of file config.c.
References utils_config_get_int().
Referenced by _arax_init(), and async_meta_init_once().
utils_config_get_int()
int utils_config_get_int (char * path, const char * key, int * value, int def_val)
Get value corresponding to key as an integer
Will search the path file for a key/value pair matching the key. If during the search any error occurs, 0 will be returned and a message will be printed on stderr. If the value is found it will be converted to an integer using atoi() and the result will be assigned to val. If no value is found val will be assigned def_val and 0 will be returned.
Note
This is a very slow function, use it only during initialization.
Parameters
path Config path.
key c style string string, with the key of interest.
value pointer to allocated array of size value_size.
def_val Default value in case the key is not found.
Returns
Zero on failure.
Definition at line 124 of file config.c.
References utils_config_get_long().
Referenced by utils_config_get_bool().
utils_config_get_long()
int utils_config_get_long (char * path, const char * key, long * value, long def_val)
Get value corresponding to key as a long
Will search the path file for a key/value pair matching the key. If during the search any error occurs, 0 will be returned and a message will be printed on stderr. If the value is found it will be converted to a long using strtol() and the result will be assigned to val. If no value is found val will be assigned def_val and 0 will be returned.
Note
This is a very slow function, use it only during initialization.
Parameters
path Config path.
key c style string string, with the key of interest.
value pointer to allocated array of size value_size.
def_val Default value in case the key is not found.
Returns
Zero on failure.
Definition at line 140 of file config.c.
References _utils_config_get_str(), and utils_config_write_long().
Referenced by utils_config_get_int(), and utils_config_get_size().
utils_config_get_size()
int utils_config_get_size (char * path, const char * key, size_t * value, size_t def_val)
Get value corresponding to key as a size_t
Value is retrieved with utils_config_get_long(). If acquired value value is in [SIZE_MAX,0] it is assigned to val and 1 is returned.
Otherwise 0 is returned and val is assigned def_val.
Note
This function only works for numbers <= 2^63.
Parameters
path Config path.
key c style string string, with the key of interest.
value pointer to allocated array of size value_size.
def_val Default value in case value was not found/appropriate.
Returns
Zero on failure.
Definition at line 160 of file config.c.
References utils_config_get_long().
Referenced by _arax_init().
utils_config_get_str()
int utils_config_get_str (char * path, const char * key, char * value, size_t value_size, const char * def_val)
Get value corresponding to key as a string
Will search the path file for a key/value pair matching the key. If the value is not found 0 will be returned. If during the search any error occurs, 0 will be returned and a message will be printed on stderr.
Note
This is a very slow function, use it only during initialization.
Parameters
path Config path, returned by utils_config_alloc_path.
key c style string string, with the key of interest.
value pointer to allocated array of size value_size.
value_size Size of value array, in bytes.
def_val Default value in case the key is not found.
Returns
Zero on failure.
Definition at line 98 of file config.c.
References _utils_config_get_str(), and utils_config_write_str().
Referenced by _arax_init(), arax_clean(), and async_meta_init_always().
utils_config_write_long()
void utils_config_write_long (char * path, const char * key, long value)
Definition at line 13 of file config.c.
Referenced by utils_config_get_long().
utils_config_write_str()
void utils_config_write_str (char * path, const char * key, const char * value)
Definition at line 22 of file config.c.
Referenced by utils_config_get_str().