Arax: Initialization/Cleanup
Initialization/Cleanup
Functions
arax_pipe_s * arax_init ()
void arax_exit ()
int arax_clean ()
Detailed Description
Functions responsible for Arax initialzation and cleanup.
Function Documentation
arax_clean()
int arax_clean ()
Clean/delete shared segment.
Note
This should only be called when there are no uses of the shared segment.
Behaviour undefined if called with processes accessing the shared segment.
Returns
Returns true if the shared semgent file was succesfully deleted.
Definition at line 211 of file impl.c.
References arax_assert, config_path, shm_file, utils_config_alloc_path(), utils_config_free_path(), and utils_config_get_str().
Referenced by arax_exit().
arax_exit()
void arax_exit ()
Exit and cleanup Arax.
Definition at line 175 of file impl.c.
References arax_assert, arax_clean(), arax_pipe_exit(), arax_pipe_get_available_size(), arax_pipe_mark_unmap(), arax_state, system_process_id(), and utils_config_free_path().
arax_init()
arax_pipe_s * arax_init ()
Initialize Arax.
This should be called by all applications prior to using any other Arax function.
Returns
A arax_pipe_s instance
Definition at line 151 of file impl.c.
References _arax_init().
Referenced by arax_plot_register_metric(), and arax_ptr_valid().