/* Dynamicaly generated file, do not modify */
#ifndef VINE_TALK_BUILD_CONFIG_HEADER
#define VINE_TALK_BUILD_CONFIG_HEADER
#define UTILS_QUEUE_CAPACITY @UTILS_QUEUE_CAPACITY@
#define CONF_CACHE_LINE @CONF_CACHE_LINE@
#define VINE_TALK_GIT_REV "@VINE_TALK_GIT_REV@"
#define CONF_VINE_MMAP_BASE @CONF_VINE_MMAP_BASE@
#cmakedefine ALLOC_STATS
#cmakedefine BREAKS_ENABLE
#cmakedefine TRACE_ENABLE
#cmakedefine VINE_TELEMETRY
#cmakedefine MMAP_POPULATE
#define VINE_CONFIG_FILE "@VINE_CONFIG_FILE@"
#define VINE_OBJECT_NAME_SIZE @VINE_OBJECT_NAME_SIZE@
#cmakedefine VINE_DATA_ANNOTATE
#endif
