/* Dynamicaly generated file, do not modify */
#ifndef VINE_TALK_BUILD_CONFIG_HEADER
#define VINE_TALK_BUILD_CONFIG_HEADER
#define UTILS_QUEUE_CAPACITY (@UTILS_QUEUE_CAPACITY@)
#define CONF_CACHE_LINE (@CONF_CACHE_LINE@)
#define VINE_TALK_GIT_REV "@VINE_TALK_GIT_REV@"
#define VINE_TALK_GIT_BRANCH "@VINE_TALK_GIT_BRANCH@"
#define CONF_VINE_MMAP_BASE @CONF_VINE_MMAP_BASE@
#cmakedefine ALLOC_STATS
#define ALLOC_PART_MB (@ALLOC_PART_MB@)
#cmakedefine TRACE_ENABLE
#cmakedefine MMAP_POPULATE
#cmakedefine VINE_REF_DEBUG
#define VINE_REF_DEBUG_MASK (@VINE_REF_DEBUG_MASK@)
#cmakedefine VINE_THROTTLE_DEBUG
#define VINE_CONFIG_FILE "@VINE_CONFIG_FILE@"
#define VINE_OBJECT_NAME_SIZE @VINE_OBJECT_NAME_SIZE@
#define VINE_KV_CAP (@VINE_KV_CAP@)
#define VINE_PROC_MAP_SIZE (@VINE_PROC_MAP_SIZE@)
#cmakedefine VINE_DATA_ANNOTATE
#endif
