if(JAVA_WRAPS)
  include(UseJava)
  file(GLOB JAR_FILES . "${CMAKE_CURRENT_SOURCE_DIR}/Java/*.jar")
  set(CMAKE_JAVA_JAR_ENTRY_POINT hello)
  foreach(JAR_PATH ${JAR_FILES})
    get_filename_component(JAR_FILE ${JAR_PATH} NAME)
    set(CP_JARS "${JAR_FILE} ${CP_JARS}")
    set(JAR_PATHS "${JAR_PATH} ${JAR_PATHS}")
  endforeach()
  set(CMAKE_JAVA_INCLUDE_PATH "${JAR_FILES}")
  file(GLOB java_srcs . "${CMAKE_CURRENT_SOURCE_DIR}/Java/*.java")
  add_jar(JArax ${java_srcs} MANIFEST "${CMAKE_CURRENT_SOURCE_DIR}/Java/Manifest")
  file(COPY ${JAR_FILES} DESTINATION ${CMAKE_BINARY_DIR})
  include_directories(${JAVA_HOME}/include)
  include_directories(${JAVA_HOME}/include/linux)
  set(CMAKE_C_FLAGS_DEBUG "-z noexecstack ${CMAKE_C_FLAGS_DEBUG}")
endif()
