#!/bin/bash
# stage 1 pre-commit - called right after a cmake configure
set -e

if [ ! -d .miniconda ]
then
	# No miniconda found, install it and pre-commit
	curl -o Miniconda3-latest-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
	chmod +x Miniconda3-latest-Linux-x86_64.sh
	./Miniconda3-latest-Linux-x86_64.sh -b -f -p .miniconda
	.miniconda/bin/conda run pip install pre-commit
	.miniconda/bin/conda run conda install -c conda-forge uncrustify
fi

# Let pre-commit generate its hook (stage 3)
.miniconda/bin/conda run pre-commit install -f --install-hooks

# Move stage 3 at pre-commit.py
mv .git/hooks/pre-commit .git/hooks/pre-commit.py # Move generated pre-commit

# Create stage 2 hook, wrap/run stage 3 inside conda
cat << EOF > .git/hooks/pre-commit
#!/bin/bash
.miniconda/bin/conda run python .git/hooks/pre-commit.py
EOF

# Make stage 2 executable
chmod +x .git/hooks/pre-commit

# This time have to call stage 2 explicitly
.git/hooks/pre-commit
